services:
  gaiverland-placeholder:
    image: alpine:3.19
    container_name: gaiverland-placeholder
    restart: "no"
    command: echo "placeholder"

networks:
  caleope-public:
    external: true
